<?xml version="1.0" encoding="UTF-8" ?>
<!--内部DTD-->
<!--<!DOCTYPE students[-->
<!--        <!ELEMENT students (student+)>-->
<!--        <!ELEMENT student (name,age?,score*)>-->
<!--        <!ATTLIST student id CDATA #REQUIRED>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ATTLIST name firstName CDATA #IMPLIED>-->
<!--        <!ELEMENT age (#PCDATA)>-->
<!--        <!ATTLIST age xuAge CDATA #FIXED "20">-->
<!--        <!ELEMENT score (#PCDATA)>-->
<!--        <!ATTLIST score sel (60|80|100) #REQUIRED>-->
<!--        ]>-->

<!-- 引入外部的dtd-->
<!DOCTYPE students SYSTEM "student.dtd">
<students>
    <student id="1">
        <name>闫昊</name>
        <age xuAge="20">21</age>
        <score sel="60">59</score>
    </student>
</students>